/**
 * Delphi Instance Registry
 * This is a sample client side  for Delphi Instance Registry.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model

case class InstanceID (
  ID: Option[Long]
)
